# Generated by Django 5.0.4 on 2024-04-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaissance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='facial_recognition_results/')),
                ('similarity_score', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmbeddingModel',
        ),
    ]
